### ISSUE TITLE
ModuleNotFoundError after `pip install -r requirements.txt`.

### ISSUE THREAD

**Issue by ken4647** [ARMmbed/DAPLink#1084]
```bash
❯ progen generate -t make_gcc_arm --clean -v --parallel stm32f103xb_bl
Traceback (most recent call last):
  File "/home/jsun/cubemx/DAPLink/venv/bin/progen", line 5, in <module>
    from project_generator.__main__ import main
  File "/home/jsun/cubemx/DAPLink/venv/lib/python3.12/site-packages/project_generator/__main__.py", line 19, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

`setup-tools` is needed to be installed:
```bash
pip install setuptools
```

Why is it not in requirements.txt?

**Comment by microbit-carlos** [comment]
Which version of Python and pip are you using? did you install dependencies in a virtual environment? if so, how did you create the virtual environment?
There has been recent updates to Python, pip and virtual environments that might affect what's installed by default when a new venv is created.

I believe Python 3.12 has also deprecated `pkg_resources` and moved it to `setuptools`.

`pip freeze` historically has excluded packages needed by pip itself, like `setuptools`, as they were always available. This is no longer the case since PEP 517 (build system requirements are now listed in pyproject.toml), and projects need to update their dependencies to reflect that. In this case it's possible `project_generator` has already updated its dependencies, but the requirements.txt from DAPLink might be pointing to an older version without this fix.

If there are no breaking changes it might be better to simply upgrade `project_generator` to the latest version (assuming it's fixed there, otherwise we can submit a patch).
