### ISSUE TITLE
TWR-KV58F220M in Windows 10

### ISSUE THREAD

**Issue by shoiti** [ARMmbed/DAPLink#490]
Hi
I am trying to connect TWR-KV58F220M on Windows 10 with MCUXpresso IDE
I thing I need to update the Firmware, but
The OpenSDA version / bootloader is CMSIS-DAP-BOOTLOADERV2.1 from NXP.com
The Firmware Application is unavalible on NXP.com

**Comment by flit** [comment]
Hi @shoiti. The OpenSDA firmware for KV58F was built using the "mbed CMSIS-DAP" project, the ancestor of DAPLink. Unfortunately, KV58F support was never migrated to DAPLink. Thus, there is not currently any version of the firmware for KV58F that supports Windows 10.

We will work on adding KV58F support to DAPLink as soon as possible. This will not be immediately, due to a number of other high priority tasks, but it's in the queue.

In the meantime, debug support (the CMSIS-DAP protocol) should work fine on Windows 10 with the current KV58F firmware. It's only flash programming via USB mass storage that should have issues. You should be able to program device flash using the debugger in MCUXpresso IDE. If debugging also doesn't work, please let me know. (Not that I could fix it any sooner, but it would be good to understand the scope of the problem.)

cc @mmahadevan108 @brianesquilona
