### ISSUE TITLE
Monitor Mode Debugging

### ISSUE THREAD

**Issue by Cheong2K** [ARMmbed/DAPLink#586]
The nRF52 MCU has MMD feature that is able to debug BLE applications without dropping the active BLE link to the host. Does DAPLink support this, too?

**Comment by flit** [comment]
No it does not. MMD is a proprietary feature of the Segger J-Link (not specific nRF52). It's an interesting idea, though. But it's really a feature that would be implemented by pyOCD rather than DAPLink, and it would be a totally independent implementation, not incompatible with Segger's MMD. I'm putting a remote debug monitor on the future features list for pyOCD. Thanks for pointing it out!
