### ISSUE TITLE
#include does not have the correct case

### ISSUE THREAD

**Issue by lwalkera** [ARMmbed/DAPLink#654]
https://github.com/ARMmbed/DAPLink/blob/master/source/rtos_none/SysTick_Handler.c#L22
https://github.com/ARMmbed/DAPLink/blob/master/source/rtos_none/cmsis_os2_port.c
Fails to compile on case-sensitive systems because Systick_Handler.h != SysTick_Handler.h.

**Comment by 0xc0170** [comment]
Looking at the files: https://github.com/ARMmbed/DAPLink/tree/master/source/rtos_none , I don't see any mistake there.

`SysTick_handler.h` is not included but proper `SysTick_Handler.h` is also in the files above.

We test mac OS/win/linux so should have seen these previously?

**Comment by lwalkera** [comment]
The #define is "Systick_Handler.h" it should be "Sys**T**ick_Handler.h"

**Comment by 0xc0170** [comment]
Now spotted ! Please send PR fixing the issue

**Comment by 0xc0170** [comment]
I'll fix it later today

**Comment by flit** [comment]
@0xc0170 I think the reason this wasn't seen before is that CI only builds on Windows, then tests on the 3 OSes. Before mbed-cli based building was supported, building on Windows was the only option because it required Keil MDK. Now we do have the option to build on all 3 OSes, assuming we had an AC5 compiler.
